"""align indexes and constraints with design

Revision ID: 5aa227e00edd
Revises: a8c4f2d91b6e
Create Date: 2026-07-24 13:11:02.500310

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5aa227e00edd"
down_revision: Union[str, Sequence[str], None] = "a8c4f2d91b6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applied_coupon_snapshots", "created_at")
    op.drop_column("applied_coupon_snapshots", "updated_at")
    op.create_index("ix_cart_items_cart_id", "cart_items", ["cart_id"], unique=False)
    op.create_index(
        "ix_cart_items_menu_item_id", "cart_items", ["menu_item_id"], unique=False
    )
    op.create_index("ix_carts_customer_id", "carts", ["customer_id"], unique=False)
    op.create_index(
        "ix_carts_customer_status", "carts", ["customer_id", "status"], unique=False
    )
    op.create_index("ix_carts_restaurant_id", "carts", ["restaurant_id"], unique=False)
    op.create_index(
        "uq_carts_customer_active",
        "carts",
        ["customer_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_check_constraint(
        "ck_customers_first_name_not_empty", "customers", "first_name <> ''"
    )
    op.create_check_constraint(
        "ck_customers_last_name_not_empty", "customers", "last_name <> ''"
    )
    op.drop_column("delivery_address_snapshots", "created_at")
    op.drop_column("delivery_address_snapshots", "updated_at")
    op.alter_column(
        "food_item_review_images",
        "uploaded_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.create_check_constraint(
        "ck_menu_items_price_non_negative", "menu_items", "price >= 0"
    )
    op.create_check_constraint(
        "ck_menu_items_preparation_time_positive", "menu_items", "preparation_time > 0"
    )
    op.create_check_constraint(
        "ck_menu_items_name_not_empty", "menu_items", "name <> ''"
    )
    op.create_check_constraint(
        "ck_menu_items_category_not_empty", "menu_items", "category <> ''"
    )
    op.create_index("ix_menu_items_category", "menu_items", ["category"], unique=False)
    op.create_index(
        "ix_menu_items_is_available", "menu_items", ["is_available"], unique=False
    )
    op.create_index("ix_menu_items_name", "menu_items", ["name"], unique=False)
    op.create_index(
        "ix_menu_items_restaurant_id", "menu_items", ["restaurant_id"], unique=False
    )
    op.create_index(
        "ix_notifications_created_at", "notifications", ["created_at"], unique=False
    )
    op.create_index(
        "ix_notifications_customer_id", "notifications", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_notifications_customer_is_read",
        "notifications",
        ["customer_id", "is_read"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_is_read", "notifications", ["is_read"], unique=False
    )
    op.create_index(
        "ix_order_items_menu_item_id", "order_items", ["menu_item_id"], unique=False
    )
    op.create_index(
        "ix_order_items_order_id", "order_items", ["order_id"], unique=False
    )
    op.drop_column("order_items", "updated_at")
    op.alter_column(
        "order_status_history",
        "changed_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.create_index(
        "ix_order_status_history_changed_at",
        "order_status_history",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        "ix_order_status_history_order_id",
        "order_status_history",
        ["order_id"],
        unique=False,
    )
    op.create_check_constraint(
        "ck_orders_subtotal_non_negative", "orders", "subtotal >= 0"
    )
    op.create_check_constraint(
        "ck_orders_discount_amount_non_negative", "orders", "discount_amount >= 0"
    )
    op.create_check_constraint(
        "ck_orders_delivery_fee_non_negative", "orders", "delivery_fee >= 0"
    )
    op.create_check_constraint(
        "ck_orders_tax_amount_non_negative", "orders", "tax_amount >= 0"
    )
    op.create_check_constraint(
        "ck_orders_grand_total_non_negative", "orders", "grand_total >= 0"
    )
    op.create_check_constraint(
        "ck_orders_payment_method", "orders", "payment_method IN ('ONLINE', 'COD')"
    )
    op.create_index("ix_orders_created_at", "orders", ["created_at"], unique=False)
    op.create_index(
        "ix_orders_current_status", "orders", ["current_status"], unique=False
    )
    op.create_index("ix_orders_customer_id", "orders", ["customer_id"], unique=False)
    op.create_index(
        "ix_orders_restaurant_id", "orders", ["restaurant_id"], unique=False
    )
    op.create_index(
        "ix_platform_coupons_status", "platform_coupons", ["status"], unique=False
    )
    op.create_index(
        "ix_platform_coupons_valid_until",
        "platform_coupons",
        ["valid_until"],
        unique=False,
    )
    op.create_index(
        "ix_restaurant_coupons_restaurant_id",
        "restaurant_coupons",
        ["restaurant_id"],
        unique=False,
    )
    op.create_index(
        "ix_restaurant_coupons_status", "restaurant_coupons", ["status"], unique=False
    )
    op.create_index(
        "ix_restaurant_coupons_valid_until",
        "restaurant_coupons",
        ["valid_until"],
        unique=False,
    )
    op.create_check_constraint(
        "ck_restaurants_restaurant_name_not_empty",
        "restaurants",
        "restaurant_name <> ''",
    )
    op.create_check_constraint(
        "ck_restaurants_opening_before_closing",
        "restaurants",
        "opening_time < closing_time",
    )
    op.create_check_constraint(
        "ck_restaurants_average_rating_range",
        "restaurants",
        "average_rating BETWEEN 0 AND 5",
    )
    op.create_index(
        "ix_restaurants_average_rating", "restaurants", ["average_rating"], unique=False
    )
    op.create_index("ix_restaurants_city", "restaurants", ["city"], unique=False)
    op.create_index(
        "ix_restaurants_cuisine_type", "restaurants", ["cuisine_type"], unique=False
    )
    op.create_index(
        "ix_restaurants_is_active", "restaurants", ["is_active"], unique=False
    )
    op.create_index(
        "ix_restaurants_restaurant_name",
        "restaurants",
        ["restaurant_name"],
        unique=False,
    )
    op.alter_column(
        "restaurant_review_images",
        "uploaded_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.create_check_constraint(
        "ck_saved_addresses_recipient_name_not_empty",
        "saved_addresses",
        "recipient_name <> ''",
    )
    op.create_check_constraint(
        "ck_saved_addresses_street_not_empty", "saved_addresses", "street <> ''"
    )
    op.create_check_constraint(
        "ck_saved_addresses_city_not_empty", "saved_addresses", "city <> ''"
    )
    op.create_check_constraint(
        "ck_saved_addresses_state_not_empty", "saved_addresses", "state <> ''"
    )
    op.create_check_constraint(
        "ck_saved_addresses_postal_code_not_empty",
        "saved_addresses",
        "postal_code <> ''",
    )
    op.create_index(
        "ix_saved_addresses_customer_default",
        "saved_addresses",
        ["customer_id", "is_default"],
        unique=False,
    )
    op.create_index(
        "ix_saved_addresses_customer_id",
        "saved_addresses",
        ["customer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_saved_addresses_customer_id", table_name="saved_addresses")
    op.drop_index("ix_saved_addresses_customer_default", table_name="saved_addresses")
    op.drop_constraint(
        "ck_saved_addresses_postal_code_not_empty", "saved_addresses", type_="check"
    )
    op.drop_constraint(
        "ck_saved_addresses_state_not_empty", "saved_addresses", type_="check"
    )
    op.drop_constraint(
        "ck_saved_addresses_city_not_empty", "saved_addresses", type_="check"
    )
    op.drop_constraint(
        "ck_saved_addresses_street_not_empty", "saved_addresses", type_="check"
    )
    op.drop_constraint(
        "ck_saved_addresses_recipient_name_not_empty", "saved_addresses", type_="check"
    )
    op.alter_column(
        "restaurant_review_images",
        "uploaded_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_restaurants_restaurant_name", table_name="restaurants")
    op.drop_index("ix_restaurants_is_active", table_name="restaurants")
    op.drop_index("ix_restaurants_cuisine_type", table_name="restaurants")
    op.drop_index("ix_restaurants_city", table_name="restaurants")
    op.drop_index("ix_restaurants_average_rating", table_name="restaurants")
    op.drop_constraint(
        "ck_restaurants_average_rating_range", "restaurants", type_="check"
    )
    op.drop_constraint(
        "ck_restaurants_opening_before_closing", "restaurants", type_="check"
    )
    op.drop_constraint(
        "ck_restaurants_restaurant_name_not_empty", "restaurants", type_="check"
    )
    op.drop_index("ix_restaurant_coupons_valid_until", table_name="restaurant_coupons")
    op.drop_index("ix_restaurant_coupons_status", table_name="restaurant_coupons")
    op.drop_index(
        "ix_restaurant_coupons_restaurant_id", table_name="restaurant_coupons"
    )
    op.drop_index("ix_platform_coupons_valid_until", table_name="platform_coupons")
    op.drop_index("ix_platform_coupons_status", table_name="platform_coupons")
    op.drop_index("ix_orders_restaurant_id", table_name="orders")
    op.drop_index("ix_orders_customer_id", table_name="orders")
    op.drop_index("ix_orders_current_status", table_name="orders")
    op.drop_index("ix_orders_created_at", table_name="orders")
    op.drop_constraint("ck_orders_payment_method", "orders", type_="check")
    op.drop_constraint("ck_orders_grand_total_non_negative", "orders", type_="check")
    op.drop_constraint("ck_orders_tax_amount_non_negative", "orders", type_="check")
    op.drop_constraint("ck_orders_delivery_fee_non_negative", "orders", type_="check")
    op.drop_constraint(
        "ck_orders_discount_amount_non_negative", "orders", type_="check"
    )
    op.drop_constraint("ck_orders_subtotal_non_negative", "orders", type_="check")
    op.drop_index("ix_order_status_history_order_id", table_name="order_status_history")
    op.drop_index(
        "ix_order_status_history_changed_at", table_name="order_status_history"
    )
    op.alter_column(
        "order_status_history",
        "changed_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "order_items",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("ix_order_items_order_id", table_name="order_items")
    op.drop_index("ix_order_items_menu_item_id", table_name="order_items")
    op.drop_index("ix_notifications_is_read", table_name="notifications")
    op.drop_index("ix_notifications_customer_is_read", table_name="notifications")
    op.drop_index("ix_notifications_customer_id", table_name="notifications")
    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.drop_index("ix_menu_items_restaurant_id", table_name="menu_items")
    op.drop_index("ix_menu_items_name", table_name="menu_items")
    op.drop_index("ix_menu_items_is_available", table_name="menu_items")
    op.drop_index("ix_menu_items_category", table_name="menu_items")
    op.drop_constraint("ck_menu_items_category_not_empty", "menu_items", type_="check")
    op.drop_constraint("ck_menu_items_name_not_empty", "menu_items", type_="check")
    op.drop_constraint(
        "ck_menu_items_preparation_time_positive", "menu_items", type_="check"
    )
    op.drop_constraint("ck_menu_items_price_non_negative", "menu_items", type_="check")
    op.alter_column(
        "food_item_review_images",
        "uploaded_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "delivery_address_snapshots",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "delivery_address_snapshots",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("ck_customers_last_name_not_empty", "customers", type_="check")
    op.drop_constraint("ck_customers_first_name_not_empty", "customers", type_="check")
    op.drop_index(
        "uq_carts_customer_active",
        table_name="carts",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index("ix_carts_restaurant_id", table_name="carts")
    op.drop_index("ix_carts_customer_status", table_name="carts")
    op.drop_index("ix_carts_customer_id", table_name="carts")
    op.drop_index("ix_cart_items_menu_item_id", table_name="cart_items")
    op.drop_index("ix_cart_items_cart_id", table_name="cart_items")
    op.add_column(
        "applied_coupon_snapshots",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "applied_coupon_snapshots",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
